/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeRouteImport } from './routes/he'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HeIndexRouteImport } from './routes/he.index'
import { Route as HePortfolioRouteImport } from './routes/he.portfolio'
import { Route as HePrivacyRouteImport } from './routes/he.privacy'
import { Route as HeTermsRouteImport } from './routes/he.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeRoute = HeRouteImport.update({
  id: '/he',
  path: '/he',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HeIndexRoute = HeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeRoute,
} as any)
const HePortfolioRoute = HePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => HeRoute,
} as any)
const HePrivacyRoute = HePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => HeRoute,
} as any)
const HeTermsRoute = HeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => HeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/he': typeof HeRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/he/portfolio': typeof HePortfolioRoute
  '/he/privacy': typeof HePrivacyRoute
  '/he/terms': typeof HeTermsRoute
  '/he/': typeof HeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/he/portfolio': typeof HePortfolioRoute
  '/he/privacy': typeof HePrivacyRoute
  '/he/terms': typeof HeTermsRoute
  '/he': typeof HeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/he': typeof HeRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/he/portfolio': typeof HePortfolioRoute
  '/he/privacy': typeof HePrivacyRoute
  '/he/terms': typeof HeTermsRoute
  '/he/': typeof HeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/he'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/he/portfolio'
    | '/he/privacy'
    | '/he/terms'
    | '/he/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/he/portfolio'
    | '/he/privacy'
    | '/he/terms'
    | '/he'
  id:
    | '__root__'
    | '/'
    | '/he'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/he/portfolio'
    | '/he/privacy'
    | '/he/terms'
    | '/he/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeRoute: typeof HeRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/he': {
      id: '/he'
      path: '/he'
      fullPath: '/he'
      preLoaderRoute: typeof HeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/he/': {
      id: '/he/'
      path: '/'
      fullPath: '/he/'
      preLoaderRoute: typeof HeIndexRouteImport
      parentRoute: typeof HeRoute
    }
    '/he/portfolio': {
      id: '/he/portfolio'
      path: '/portfolio'
      fullPath: '/he/portfolio'
      preLoaderRoute: typeof HePortfolioRouteImport
      parentRoute: typeof HeRoute
    }
    '/he/privacy': {
      id: '/he/privacy'
      path: '/privacy'
      fullPath: '/he/privacy'
      preLoaderRoute: typeof HePrivacyRouteImport
      parentRoute: typeof HeRoute
    }
    '/he/terms': {
      id: '/he/terms'
      path: '/terms'
      fullPath: '/he/terms'
      preLoaderRoute: typeof HeTermsRouteImport
      parentRoute: typeof HeRoute
    }
  }
}

interface HeRouteChildren {
  HePortfolioRoute: typeof HePortfolioRoute
  HePrivacyRoute: typeof HePrivacyRoute
  HeTermsRoute: typeof HeTermsRoute
  HeIndexRoute: typeof HeIndexRoute
}

const HeRouteChildren: HeRouteChildren = {
  HePortfolioRoute: HePortfolioRoute,
  HePrivacyRoute: HePrivacyRoute,
  HeTermsRoute: HeTermsRoute,
  HeIndexRoute: HeIndexRoute,
}

const HeRouteWithChildren = HeRoute._addFileChildren(HeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeRoute: HeRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
