/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RuRouteImport } from './routes/ru'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RuIndexRouteImport } from './routes/ru.index'
import { Route as RuPortfolioRouteImport } from './routes/ru.portfolio'
import { Route as RuPrivacyRouteImport } from './routes/ru.privacy'
import { Route as RuTermsRouteImport } from './routes/ru.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuRoute,
} as any)
const RuPortfolioRoute = RuPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => RuRoute,
} as any)
const RuPrivacyRoute = RuPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => RuRoute,
} as any)
const RuTermsRoute = RuTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => RuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/ru': typeof RuRouteWithChildren
  '/terms': typeof TermsRoute
  '/ru/portfolio': typeof RuPortfolioRoute
  '/ru/privacy': typeof RuPrivacyRoute
  '/ru/terms': typeof RuTermsRoute
  '/ru/': typeof RuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ru/portfolio': typeof RuPortfolioRoute
  '/ru/privacy': typeof RuPrivacyRoute
  '/ru/terms': typeof RuTermsRoute
  '/ru': typeof RuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/ru': typeof RuRouteWithChildren
  '/terms': typeof TermsRoute
  '/ru/portfolio': typeof RuPortfolioRoute
  '/ru/privacy': typeof RuPrivacyRoute
  '/ru/terms': typeof RuTermsRoute
  '/ru/': typeof RuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portfolio'
    | '/privacy'
    | '/ru'
    | '/terms'
    | '/ru/portfolio'
    | '/ru/privacy'
    | '/ru/terms'
    | '/ru/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/ru/portfolio'
    | '/ru/privacy'
    | '/ru/terms'
    | '/ru'
  id:
    | '__root__'
    | '/'
    | '/portfolio'
    | '/privacy'
    | '/ru'
    | '/terms'
    | '/ru/portfolio'
    | '/ru/privacy'
    | '/ru/terms'
    | '/ru/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  RuRoute: typeof RuRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/portfolio': {
      id: '/ru/portfolio'
      path: '/portfolio'
      fullPath: '/ru/portfolio'
      preLoaderRoute: typeof RuPortfolioRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/privacy': {
      id: '/ru/privacy'
      path: '/privacy'
      fullPath: '/ru/privacy'
      preLoaderRoute: typeof RuPrivacyRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/terms': {
      id: '/ru/terms'
      path: '/terms'
      fullPath: '/ru/terms'
      preLoaderRoute: typeof RuTermsRouteImport
      parentRoute: typeof RuRoute
    }
  }
}

interface RuRouteChildren {
  RuPortfolioRoute: typeof RuPortfolioRoute
  RuPrivacyRoute: typeof RuPrivacyRoute
  RuTermsRoute: typeof RuTermsRoute
  RuIndexRoute: typeof RuIndexRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuPortfolioRoute: RuPortfolioRoute,
  RuPrivacyRoute: RuPrivacyRoute,
  RuTermsRoute: RuTermsRoute,
  RuIndexRoute: RuIndexRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  RuRoute: RuRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
